[project]
name = "baseProject"
stage = "development"
port = 8888
secretKey = "haner27"

[mysql]
ip = "127.0.0.1"
port = 3306
username = "root"
password = "haner27"
database = "hnf"

[redis]
ip = "127.0.0.1"
port = 6379